from flask import Flask, request, jsonify
import os
from datetime import datetime
import json
import openai

app = Flask(__name__)

# Env vars (set in Render dashboard)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', 'sk-placeholder')
WP_BASE_URL = os.environ.get('WP_BASE_URL', 'https://demo.wp.com')
SEMRUSH_API_KEY = os.environ.get('SEMRUSH_API_KEY', 'placeholder')
GBP_LOCATION_ID = os.environ.get('GBP_LOCATION_ID', '123')
GA4_PROPERTY_ID = os.environ.get('GA4_PROPERTY_ID', 'placeholder')

# Configure OpenAI
openai.api_key = OPENAI_API_KEY
USE_REAL_AI = OPENAI_API_KEY not in ['sk-placeholder', 'placeholder', '']

# Industry-specific content templates
INDUSTRY_TEMPLATES = {
    'vr_gaming': {
        'focus': 'VR studios, gaming companies, immersive tech',
        'tone': 'innovative, forward-thinking, tech-savvy',
        'cta': 'Join the VR revolution in Sarasota',
        'stats_emphasis': 'creative tech talent, Ringling pipeline'
    },
    'tech_startups': {
        'focus': 'software development, SaaS, tech innovation',
        'tone': 'entrepreneurial, dynamic, growth-focused',
        'cta': 'Scale your startup in Sarasota',
        'stats_emphasis': 'funding ecosystem, talent availability'
    },
    'construction': {
        'focus': 'construction updates, real estate development',
        'tone': 'authoritative, detailed, progress-oriented',
        'cta': 'Follow our development progress',
        'stats_emphasis': 'economic growth, infrastructure investment'
    },
    'healthcare': {
        'focus': 'medical practices, healthcare services',
        'tone': 'professional, trustworthy, community-focused',
        'cta': 'Discover healthcare innovation in Sarasota',
        'stats_emphasis': 'quality of life, healthcare infrastructure'
    }
}

def generate_ai_blog(keyword, quote, geo, industry='vr_gaming', word_count=1200):
    """
    Generate blog content using OpenAI GPT-4
    Falls back to enhanced template if API not configured
    """
    
    if not USE_REAL_AI:
        # Enhanced template fallback
        return generate_template_blog(keyword, quote, geo, industry, word_count)
    
    try:
        template = INDUSTRY_TEMPLATES.get(industry, INDUSTRY_TEMPLATES['vr_gaming'])
        
        prompt = f"""Generate a comprehensive, SEO-optimized blog post for EDC Sarasota's Innovation Engine.

SPECIFICATIONS:
- Topic: {keyword} in {geo}
- Industry Focus: {template['focus']}
- Tone: {template['tone']}
- Word Count: {word_count} words minimum
- Target Audience: Business decision-makers considering relocation

REQUIRED ELEMENTS:
1. Compelling headline using the keyword
2. Hook paragraph featuring this quote: "{quote}"
3. Overview of {geo}'s tech ecosystem
4. Key statistics to include:
   - 175% IT sector growth (5-year trend)
   - 830 established technology firms
   - $130,000 average tech compensation
   - 50+ annual business relocations
   - 200+ jobs created through EDC initiatives
5. "Why Relocate to {geo}?" section with 5-7 specific benefits
6. EDC support services overview
7. Success stories and testimonials (generic, aspirational)
8. Strong call-to-action: {template['cta']}
9. FAQ section (4-5 questions) suitable for FAQ schema markup

SEO REQUIREMENTS:
- Use H2 and H3 headers strategically
- Include keyword naturally (1-2% density)
- Add internal link suggestions in [brackets]
- Meta description ready (155 characters)
- Image alt text suggestions

STYLE:
- Professional but approachable
- Data-driven with specific metrics
- Action-oriented language
- Emphasize {template['stats_emphasis']}

OUTPUT FORMAT: Markdown with proper headers, bold emphasis, bullet points where appropriate.

Generate the complete blog post now:"""

        response = openai.ChatCompletion.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are an expert content strategist specializing in economic development and business relocation content. Write compelling, SEO-optimized blog posts that drive action."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=2500
        )
        
        blog_content = response.choices[0].message.content
        
        # Add MCP signature
        blog_content += "\n\n*Generated by MCP Framework – EDC Innovation Engine*"
        
        return blog_content
        
    except Exception as e:
        print(f"OpenAI API Error: {e}")
        # Fallback to template
        return generate_template_blog(keyword, quote, geo, industry, word_count)

def generate_template_blog(keyword, quote, geo, industry, word_count):
    """
    Enhanced template-based blog generation
    Used as fallback or when OpenAI not configured
    """
    template = INDUSTRY_TEMPLATES.get(industry, INDUSTRY_TEMPLATES['vr_gaming'])
    
    # Expanded template content (still 800+ words)
    blog_content = f"""# {keyword} in {geo}: The Innovation Engine

"{quote}" – This isn't just a tagline. It's the reality transforming {geo} into a tech powerhouse for {template['focus']}.

## The {geo} Advantage for {keyword}

With **175% IT sector growth** and **830 technology firms** calling {geo} home, the region has become a magnet for innovative companies. Average tech wages reach **$130,000**, reflecting the high-value talent pool and thriving ecosystem that's particularly strong in {template['stats_emphasis']}.

### Why Relocate Here?

1. **Innovation Infrastructure**: World-class talent from Ringling College of Art and Design, New College of Florida, and USF Sarasota-Manatee campus
2. **Quality of Life**: Gulf Coast lifestyle meets tech-forward community – where work-life balance isn't just a buzzword
3. **Business Climate**: Pro-growth policies, competitive tax advantages, and dedicated EDC support for {template['focus']}
4. **Market Access**: Tampa Bay proximity (60 minutes) with small-town advantages and lower costs
5. **Talent Pipeline**: Growing pool of tech-savvy professionals attracted by lifestyle and opportunity
6. **Infrastructure**: Fiber connectivity, modern office spaces, and expanding co-working facilities
7. **Community**: Thriving tech meetups, networking events, and collaborative ecosystem

### The Numbers Tell the Story

Our {geo} tech ecosystem delivers compelling metrics that drive relocation decisions:

- **830 tech firms** (and growing by 12% annually)
- **175% growth** in IT sector over 5 years
- **$130K average tech wage** – competitive with major metros
- **50+ major relocations** annually across all sectors
- **200+ jobs created** through EDC partnership initiatives
- **$26M economic impact** from recent tech relocations alone

These aren't just statistics – they represent real companies, real jobs, and real growth opportunities.

### EDC Support Services: Your Innovation Partner

The EDC Sarasota Innovation Engine provides comprehensive support throughout your relocation journey:

**Pre-Relocation:**
- Market research and competitive analysis
- Site selection assistance with local commercial real estate partners
- Demographic and workforce studies
- Incentive program navigation (state and local)

**During Transition:**
- Permitting and regulatory guidance
- Talent recruitment assistance
- Community integration support
- Introduction to key stakeholders and partners

**Post-Relocation:**
- Ongoing business development support
- Networking and collaboration opportunities
- Expansion planning assistance
- Success metric tracking and reporting

### Success Stories in {template['focus']}

Companies choosing {geo} for {template['focus']} consistently report transformative results:

- **Faster Time-to-Market**: Reduced bureaucracy and streamlined processes mean quicker launches
- **Enhanced Talent Retention**: Quality of life factors lead to 30-40% better retention rates
- **Lower Operational Costs**: 20-30% savings vs. major tech hubs while maintaining quality
- **Higher Quality of Life**: Teams report better work-life balance and satisfaction
- **Stronger Community Ties**: Easier to build meaningful business relationships in a collaborative ecosystem

*"The decision to relocate to {geo} was transformative for our business. The combination of talented workforce, supportive business climate, and exceptional quality of life has exceeded our expectations."* – Representative {template['focus']} company testimonial

### Real Estate and Facilities

{geo}'s commercial real estate market offers diverse options for {template['focus']}:

- **Class A Office Space**: Modern facilities with competitive rates
- **Co-working Options**: Flexible spaces for startups and remote teams  
- **Industrial/Warehouse**: Available for companies needing specialized facilities
- **Mixed-Use Developments**: Live-work-play environments attracting young talent

Average commercial lease rates run 40-50% below comparable markets while offering equal or better amenities.

### Transportation and Connectivity

- **Sarasota-Bradenton International Airport**: Direct flights to major tech hubs
- **Interstate 75 Access**: Easy logistics for physical operations
- **Fiber Infrastructure**: Carrier-grade connectivity throughout business districts
- **Public Transit**: Expanding options for employee commuting

### Lifestyle Factors That Matter

Beyond business metrics, {geo} offers quality-of-life advantages that help recruit and retain top talent:

- **37 miles of beaches**: Gulf Coast access for recreation and lifestyle
- **Cultural amenities**: World-class arts, dining, and entertainment
- **Education**: Top-rated schools and educational institutions
- **Healthcare**: Excellent medical facilities including specialized care
- **Outdoor activities**: Year-round recreation from boating to golf
- **Cost of living**: Reasonable compared to major tech hubs

## Frequently Asked Questions

**Q: What incentives are available for companies relocating to {geo}?**  
A: {geo} and Florida offer various incentives including tax credits, workforce training grants, and expedited permitting. The EDC Innovation Team can guide you through available programs specific to {template['focus']}.

**Q: How long does the relocation process typically take?**  
A: With EDC support, most companies complete their relocation in 6-12 months from decision to operational. We can accelerate this timeline based on your specific needs.

**Q: What is the talent pool like for {template['focus']}?**  
A: {geo}'s talent pool is growing rapidly, with particular strength in {template['stats_emphasis']}. We can also help recruit talent from nearby markets or assist with relocation for key employees.

**Q: How does {geo} compare to other tech markets?**  
A: {geo} offers a unique combination of competitive costs (40-50% lower than major metros), strong talent pipeline, and exceptional quality of life – delivering better ROI for growing companies.

**Q: What is the business tax environment?**  
A: Florida has no state income tax, and {geo} offers various local incentives. Overall tax burden for businesses is significantly lower than most comparable markets.

## Ready to Relocate?

{template['cta']}. Contact EDC Sarasota's Innovation Team to explore how {geo} can accelerate your growth. 

From {template['focus']} to established enterprises, tech innovators are choosing to **play here and build here**.

**Next Steps:**
1. Schedule a site visit and community tour
2. Meet with EDC Innovation Team for customized analysis
3. Connect with local business leaders in your sector
4. Explore available facilities and incentive programs

**Contact EDC Sarasota:**  
[Schedule consultation] | [Download relocation guide] | [View available properties]

---

*Generated by MCP Framework – EDC Innovation Engine*  
*Leveraging AI to accelerate economic development through compelling content*
"""
    
    return blog_content

def generate_dalle_image(keyword, geo, style='professional'):
    """
    Generate header image using DALL-E
    Falls back to placeholder if not configured
    """
    
    if not USE_REAL_AI:
        return {
            'url': 'https://via.placeholder.com/1200x630.png?text=EDC+Sarasota+Innovation+Engine',
            'alt_text': f'{keyword} in {geo} - EDC Innovation',
            'status': 'placeholder'
        }
    
    try:
        prompt = f"""Professional photograph of {geo} tech hub and innovation center. Modern office building with Gulf Coast architectural style, palm trees, blue sky, tech professionals working in bright open space. Style: {style}, photorealistic, bright and inviting. Represents {keyword} and economic development."""
        
        response = openai.Image.create(
            prompt=prompt,
            n=1,
            size="1024x1024",
            model="dall-e-3"
        )
        
        return {
            'url': response.data[0].url,
            'alt_text': f'{keyword} in {geo} - Innovation Hub',
            'status': 'generated'
        }
        
    except Exception as e:
        print(f"DALL-E Error: {e}")
        return {
            'url': 'https://via.placeholder.com/1200x630.png?text=EDC+Sarasota',
            'alt_text': f'{keyword} in {geo}',
            'status': 'fallback'
        }

@app.route('/', methods=['GET'])
def home():
    return jsonify({
        'status': 'MCP Live on Render!',
        'version': '2.0-day2-ai-enhanced',
        'timestamp': datetime.now().isoformat(),
        'agents': ['content', 'schema', 'social', 'report', 'image'],
        'demo': 'POST to /generate_relo_kit with {"keyword": "VR Relos Sarasota", "quote": "play here, build here"}',
        'endpoints': {
            '/health': 'GET - Health check',
            '/generate_relo_kit': 'POST - Generate complete EDC relo kit',
            '/generate_relo_kit_advanced': 'POST - Advanced kit with AI and images',
            '/edc_metrics': 'GET - View EDC dashboard metrics',
            '/industry_templates': 'GET - List available industry templates'
        },
        'ai_status': 'enabled' if USE_REAL_AI else 'template_mode',
        'features': {
            'openai_integration': USE_REAL_AI,
            'dalle_images': USE_REAL_AI,
            'industry_templates': len(INDUSTRY_TEMPLATES),
            'word_count_range': '800-1200+'
        }
    })

@app.route('/industry_templates', methods=['GET'])
def list_templates():
    """List available industry templates"""
    return jsonify({
        'templates': list(INDUSTRY_TEMPLATES.keys()),
        'details': INDUSTRY_TEMPLATES
    })

@app.route('/generate_relo_kit', methods=['POST'])
def generate_relo_kit():
    """
    Core MCP Agent: Generate complete relocator kit (backward compatible)
    Input: keyword, quote, geo
    Output: blog, schema, social_kit, report
    """
    data = request.json or {}
    keyword = data.get('keyword', 'VR Relos Sarasota')
    quote = data.get('quote', 'play here, build here')
    geo = data.get('geo', 'Sarasota')
    industry = data.get('industry', 'vr_gaming')
    
    try:
        # Content Agent: AI Draft with industry template
        blog_content = generate_ai_blog(keyword, quote, geo, industry, word_count=1200)
        
        # Word count
        word_count = len(blog_content.split())
        
        # Schema Agent: JSON-LD
        schema = {
            "@context": "https://schema.org",
            "@type": "LocalBusiness",
            "name": "EDC Sarasota Tech Hub",
            "description": f"{keyword} comprehensive guide for {geo}: '{quote}' - Innovation Engine for tech relocations",
            "address": {
                "@type": "PostalAddress",
                "addressLocality": geo,
                "addressRegion": "FL",
                "addressCountry": "US"
            },
            "geo": {
                "@type": "GeoCoordinates",
                "latitude": "27.3364",
                "longitude": "-82.5307"
            },
            "knowsAbout": [keyword, "tech relocations", "business development"],
            "areaServed": {
                "@type": "GeoCircle",
                "geoMidpoint": {"@type": "GeoCoordinates", "latitude": "27.3364", "longitude": "-82.5307"},
                "geoRadius": "50"
            }
        }

        # Social Agent: Multi-platform kit
        social_kit = {
            "gbp_post": {
                "content": f"{geo}'s {keyword}: '{quote}' – 175% IT growth, 830 firms, $130K wages. Relocate to innovation. Learn more! #SarasotaTech #EDCInnovation",
                "cta": "Learn More",
                "cta_url": f"{WP_BASE_URL}/relo-guide"
            },
            "fb_caption": f"🚀 Discover {keyword} in {geo}!\n\n'{quote}' isn't just our motto—it's our reality.\n\n📊 175% IT sector growth\n💼 830 tech firms\n💰 $130K average wage\n\nReady to make the move? EDC Sarasota's Innovation Engine can help. #TechRelocations #SarasotaInnovation",
            "ig_post": {
                "caption": f"Play here. Build here. Thrive here. 🌴💻\n\n{geo} welcomes {keyword} with:\n✨ 175% IT growth\n✨ 830 tech companies\n✨ $130K average wages\n\nDM us to explore relocating!\n\n#VRRelos #EDCSarasota #SarasotaTech #TechRelocations #InnovationEngine #GulfCoastTech",
                "hashtags": ["#VRRelos", "#EDCSarasota", "#SarasotaTech", "#TechRelocations", "#InnovationEngine", "#FloridaTech"]
            },
            "linkedin_post": f"{keyword} in {geo}: A Strategic Analysis\n\nKey metrics driving relocation decisions:\n• 175% IT sector growth (5-year)\n• 830 established technology firms\n• $130,000 average tech compensation\n• Ringling/USF talent pipeline\n\n'{quote}' – EDC Sarasota\n\nInterested in exploring relocation opportunities? Connect with our Innovation Team. #EconomicDevelopment #TechRelocations"
        }

        # Report Agent: Metrics dashboard data
        report = {
            "relos_tracked": 50,
            "jobs_created": 200,
            "wage_avg": 130000,
            "growth_pct": 175,
            "firms_count": 830,
            "timestamp": datetime.now().isoformat(),
            "metrics_summary": {
                "economic_impact": "$26M (200 jobs × $130K)",
                "projected_annual": "50 relocations × $750 kit = $37.5K revenue",
                "edc_subscription_value": "$24K-60K annually"
            }
        }

        # Revenue calculation
        revenue_forecast = {
            "edc_subscription": 2000,
            "relo_kits_monthly": 20,
            "kit_price": 750,
            "monthly_revenue": 2000 + (20 * 750),
            "annual_projection": (2000 + (20 * 750)) * 12
        }

        return jsonify({
            'status': 'success',
            'timestamp': datetime.now().isoformat(),
            'ai_mode': 'openai' if USE_REAL_AI else 'template',
            'input': {
                'keyword': keyword,
                'quote': quote,
                'geo': geo,
                'industry': industry
            },
            'outputs': {
                'blog': {
                    'content': blog_content,
                    'word_count': word_count,
                    'seo_ready': True,
                    'generation_method': 'openai_gpt4' if USE_REAL_AI else 'enhanced_template'
                },
                'schema': schema,
                'social_kit': social_kit,
                'report': report,
                'revenue_forecast': revenue_forecast
            },
            'next_steps': [
                'Review blog content',
                'Approve for WP publish',
                'Schedule social posts',
                'Add to EDC dashboard'
            ],
            'wp_publish_url': f"{WP_BASE_URL}/wp-json/wp/v2/posts"
        })
        
    except Exception as e:
        return jsonify({
            'status': 'error',
            'error': str(e),
            'timestamp': datetime.now().isoformat()
        }), 500

@app.route('/generate_relo_kit_advanced', methods=['POST'])
def generate_relo_kit_advanced():
    """
    Advanced kit generation with images
    """
    data = request.json or {}
    keyword = data.get('keyword', 'VR Relos Sarasota')
    quote = data.get('quote', 'play here, build here')
    geo = data.get('geo', 'Sarasota')
    industry = data.get('industry', 'vr_gaming')
    include_image = data.get('include_image', True)
    
    # Generate standard kit
    standard_response = generate_relo_kit()
    kit_data = standard_response.get_json()
    
    # Add image if requested
    if include_image:
        image_data = generate_dalle_image(keyword, geo)
        kit_data['outputs']['header_image'] = image_data
    
    return jsonify(kit_data)

@app.route('/edc_metrics', methods=['GET'])
def edc_metrics():
    """EDC Dashboard Metrics Endpoint"""
    return jsonify({
        'status': 'success',
        'dashboard': 'EDC Innovation Engine',
        'version': '2.0-day2-enhanced',
        'metrics': {
            'it_growth': '175%',
            'tech_firms': 830,
            'avg_wage': 130000,
            'annual_relos': 50,
            'jobs_created': 200
        },
        'revenue': {
            'edc_subscription': '$2,000/mo',
            'relo_kits': '20/mo × $750 = $15,000',
            'monthly_total': '$17,000',
            'annual_projection': '$204,000'
        },
        'clients': [
            {'name': '941 Dental', 'kits': 3, 'status': 'active', 'industry': 'healthcare'},
            {'name': 'AK Electrical', 'kits': 5, 'status': 'active', 'industry': 'construction'},
            {'name': 'Ritz 15th Floor', 'kits': 1, 'status': 'pending', 'industry': 'construction'}
        ],
        'capabilities': {
            'ai_content': USE_REAL_AI,
            'image_generation': USE_REAL_AI,
            'industry_templates': len(INDUSTRY_TEMPLATES),
            'max_word_count': '1200+'
        },
        'timestamp': datetime.now().isoformat()
    })

@app.route('/health', methods=['GET'])
def health():
    """Health check endpoint for Render monitoring"""
    return jsonify({
        'status': 'healthy',
        'mcp_ready': True,
        'hosting': 'render-stable',
        'version': '2.0-day2-ai-enhanced',
        'timestamp': datetime.now().isoformat(),
        'env_check': {
            'openai_key': 'configured' if USE_REAL_AI else 'placeholder',
            'wp_url': WP_BASE_URL,
            'agents_active': ['content', 'schema', 'social', 'report', 'image']
        },
        'features': {
            'ai_blog_generation': USE_REAL_AI,
            'dalle_images': USE_REAL_AI,
            'industry_templates': list(INDUSTRY_TEMPLATES.keys()),
            'word_count': '800-1200+'
        }
    })

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5000))
    app.run(host='0.0.0.0', port=port, debug=False)
